FROM ubuntu

ARG BITCOIN_VER=v0.20.0
ENV BITCOIN_VER $BITCOIN_VER

#Setup run vars

ENV NODE_PORT 8333
ENV NODE_PORT_TESTNET 18333
ENV NODE_PORT_REGTEST 18443
ENV REGTEST false
ENV TESTNET false
ENV RPC_ALLOW_IP 172.17.0.0/16
ENV RPC_PASSWORD ""
ENV RPC_PORT 8332
ENV RPC_PORT_TESTNET 18332
ENV RPC_PORT_REGTEST 18332
ENV RPC_USER admin

ENV DEBIAN_FRONTEND noninteractive
ENV BDB_PREFIX='/home/bitcoin/bitcoin-core/db4'

#Install dependencies
RUN apt-get update && apt-get install -y \
	autoconf \
	apt-utils \
	bsdmainutils \
	build-essential \
	curl \
	jq \
	vim \
	jq \
	bc \
	# bsdtar \
	libarchive-tools \
	dos2unix \
	git \
	libboost-all-dev \
	libevent-dev \
	libssl-dev \
	libtool \
	locales \
	pkg-config \
	sudo \
	&& rm -rf /var/lib/apt/lists/* \
	&& apt-get autoremove
# RUN export tar='bsdtar'

#Install locales
RUN locale-gen ${OS_LOCALE}

ENV OS_LOCALE en_US.UTF-8
ENV LANG ${OS_LOCALE}
ENV LANGUAGE en_US:en
#ENV LC_ALL ${OS_LOCALE}

#Set user
WORKDIR /
RUN adduser --disabled-password --gecos '' bitcoin && \
	adduser bitcoin sudo && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER bitcoin
#Install BITCOIN-core
WORKDIR /home/bitcoin
RUN mkdir .bitcoin && \
	#sudo git clone --branch ${BITCOIN_VER} --depth 1 https://github.com/BITCOIN/core.git bitcoin-core && \
	sudo git clone --branch ${BITCOIN_VER} --depth 1 https://github.com/bitcoin/bitcoin.git bitcoin-core && \
	cd bitcoin-core && \
	sudo ./contrib/install_db4.sh `pwd` && \
	sudo ./autogen.sh && \
	# sudo ./configure --without-gui --disable-wallet  --disable-tests  --disable-gui-tests CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768" && \
	sudo ./configure --without-gui  --disable-tests  --disable-gui-tests BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" CXXFLAGS="--param ggc-min-expand=1 --param ggc-min-heapsize=32768" && \
	sudo make && \
	sudo make install

#Copy start scripts
WORKDIR /home/bitcoin/scripts/
COPY entrypoint.sh entrypoint.sh
COPY start.sh start.sh
COPY bitcoin-start.sh bitcoin-start.sh

RUN sudo dos2unix \
	entrypoint.sh \
	start.sh \
	bitcoin-start.sh && \
	sudo chmod +x \
	entrypoint.sh \
	start.sh \
	bitcoin-start.sh && \
	sudo apt-get purge -y dos2unix && \
	sudo rm -rf /var/lib/apt/lists/*

#Create data dir
WORKDIR /home/bitcoin
RUN mkdir data && \
	cd data && \
	mkdir bitcoin &&\
	sudo rm -rf /home/bitcoin/.bitcoin && \
	sudo ln -s /home/bitcoin/data/bitcoin /home/bitcoin/.bitcoin

#Run entrypoint
WORKDIR /home/bitcoin
ENTRYPOINT ["scripts/entrypoint.sh"]

#Start bitcoin and meteor
CMD ["scripts/start.sh"]

#Expose ports
EXPOSE $NODE_PORT $RPC_PORT $RPC_PORT_REGTEST

